export const data = [
  {
    name: "Overview",
    id: "overview",
  },
  {
    name: "History",
    id: "history",
  },
  {
    name: "Statement Date",
    id: "statement_date",
  },
  {
    name: "Error Code List",
    id: "error_code",
  },
  {
    name: "Supported Currency List",
    id: "supported_currency",
  },
  {
    name: "Supported Language List",
    id: "statement_language",
  },
  {
    name: "Front-End Integration",
    id: "front_end_integration",
  },
  {
    name: "API Integration Information",
    id: "api_integration",
  },
  {
    name: "How to Launch the game",
    id: "how_to_launch",
  },
  {
    name: "Function API",
    id: "function_api",
  },
  {
    name: "Bet Detail",
    id: "bet_detail",
  },
  {
    name: "Promotion",
    id: "promotion",
  },
  {
    name: "Consolidate Report",
    id: "consolidate_report",
  },
]

export const currency = [
  "AUD",
  "CAD",
  "CHF",
  "CNY",
  "EUR",
  "GBP",
  "HKD",
  "IDR",
  "INR",
  "JPY",
  "KRW",
  "MMK",
  "MYR",
  "NOK",
  "NZD",
  "PHP",
  "SEK",
  "SGD",
  "THB",
  "USD",
  "VND",
  "ZAR",
  "KHR",
  "SAR",
  "AED",
  "RUB",
  "BRL",
  "TRY",
  "BDT",
  "BND",
  "NIO",
  "LKR",
  "NPR",
  "LAK",
  "XAF",
  "NGN",
  "KES",
  "ZMW",
  "TZS",
  "XOF",
  "PEN",
  "TND",
  "ETB",
  "ARS",
  "DKK",
  "DOP",
  "ILS",
  "MOP",
  "MXN",
  "VEF",
  "COP",
  "IRR",
  "AMD",
  "PYG",
  "MAD",
  "BOB",
  "DZD",
  "CLP",
  "VES",
  "LRD",
  "BZD",
  "UAH",
  "KZT",
  "PLN",
  "SLL",
  "SLE",
  "kIDR",
  "kVND",
  "kMMK",
  "NAD",
  "MGA",
  "ZWD",
  "TWD",
  "BGN",
  "BYN",
  "CLP",
  "CRC",
  "CUP",
  "CZK",
  "GEL",
  "GHS",
  "HUF",
  "IQD",
  "JOD",
  "KGS",
  "KWD",
  "MDL",
  "OMR",
  "PAB",
  'PKR',
  'QAR',
  'RON',
  'RWF',
  'SOS',
  'TJS',
  'TMT',
  'UGX',
  'UZS',
  'XDR',
  'SAR',
  'UYU',
  'GMD',
  'LBP',
  'MZN',
  'KPW',
  'MXV',
  'CDF',
  'ALL',
  'BWP',
  'CUC',
  'EGP',
  'RSD',
  'BAM',
  'MNT',
  'ETBB',
  'AZN',
  'GYD',
  'TOP',
  'SRD',
]

export const errorCode = [
  {code: 0, message:	"Success"},
  {code: 400, message:	"Invalid Input"},
  {code: 401, message:	"Player Not Login"},
  {code: 402, message:	"Insufficient Balance"},
  {code: 403, message:	"Bet already exists"},
  {code: 404, message:	"Bet Was Not Found"},
  {code: 405, message:	"Api Suspended"},
  {code: 406, message:	"Over Max Winning"},
  {code: 407, message:	"Over Max Lose"},
  {code: 409, message:	"Bet Already Settled"},
  {code: 410, message:	"Bet Already Cancelled"},
  {code: 3002, message:	"Report Invalid Input"},
  {code: 3003, message:	"Report Page Not Found"},
  {code: 3004, message:	"Report GameCode Not Found"},
  {code: 9999, message:	"Internal Server Error"},
  {code: 503, message:	"Under Maintenance"},
]

export const language = [
  {name: "English",	code: "EN", iso: "EN"},
  {name: "Chinese",	code: "ZH_CN", iso: "ZH"},
  {name: "Thai",	code: "TH_TH", iso: "TH"},
  {name: "Vietnamese",	code: "VI_VN", iso: "VI"},
  {name: "Indonesian",	code: "ID_ID", iso: "ID"},
  {name: "Burmese",	code: "MY_MM", iso: "MY"},
  {name: "Hindi",	code: "HI_IN", iso: "HI"},
  {name: "Malay",	code: "MS_MY", iso: "MS"},
  {name: "Korean",	code: "KO_KR", iso: "KO"},
  {name: "Japanese",	code: "JA_JP", iso: "JA"},
  {name: "German",	code: "DE_DE", iso: "DE"},
  {name: "Spanish",	code: "ES_ES", iso: "ES"},
  {name: "French",	code: "FR_FR", iso: "FR"},
  {name: "Russian",	code: "RU_RU", iso: "RU"},
  {name: "Portuguese",	code: "PT_PT", iso: "PT"},
  {name: "Latin Spanish",	code: "ES_LA", iso: "ES"},
  {name: "Portuguese",	code: "PT_BR", iso: "PT"},
  {name: "Arabic",	code: "AR_AE", iso: "AR"},
  {name: "Bangla",	code: "BN_BD", iso: "BN"},
  {name: "Turkish",	code: "TR_TR", iso: "TR"},
  {name: "English(No Gambling Sign)",	code: "EN_SC", iso: "EN"},
  {name: "Burmese(No Gambling Sign)",	code: "MM_SC", iso: "MM"},
]